export const cityList = [
  {label: 'Select City', value: ''},
  {label: 'Dubai', value: 'Dubai'},
  {label: 'Abu Dhabi', value: 'Abu Dhabi'},
  {label: 'Sharjah', value: 'Sharjah'},
  {label: 'Al Ain', value: 'Al Ain'},
  {label: 'Ajman', value: 'Ajman'},
  {label: 'Ras Al Khaimah', value: 'Ras Al Khaimah'},
  {label: 'Fujairah', value: 'Fujairah'},
  {label: 'Umm Al Quwain', value: 'Umm Al Quwain'},
  {label: 'Kalba', value: 'Kalba'},
  {label: 'Khor Fakkan', value: 'Khor Fakkan'},
  {label: 'Madinat Zayed', value: 'Madinat Zayed'},
  {label: 'Al Jazirah Al Hamra', value: 'Al Jazirah Al Hamra'},
  {label: 'Masāfī', value: 'Masāfī'},
  {label: 'Badīyah', value: 'Badīyah'},
  {label: 'Zubārah', value: 'Zubārah'},
  {label: 'Al Faq‘', value: 'Al Faq‘'},
  {label: 'Ash Sha‘m', value: 'Ash Sha‘m'},
  {label: 'Huwaylāt', value: 'Huwaylāt'},
  {label: 'Naḩwah', value: 'Naḩwah'},
  {label: 'Sharīyah', value: 'Sharīyah'},
  {label: 'Ḩaşat al Bidīyah', value: 'Ḩaşat al Bidīyah'},
  {label: 'Maşfūţ', value: 'Maşfūţ'},
  {label: 'Qarayţaysah', value: 'Qarayţaysah'},
  {label: 'Margham', value: 'Margham'},
  {label: 'Qimah', value: 'Qimah'},
  {label: '‘Ūd al Bayḑā’', value: '‘Ūd al Bayḑā’'},
  {label: 'Ferij al Muhadham', value: 'Ferij al Muhadham'},
  {label: 'Hunaywah', value: 'Hunaywah'},
  {label: 'Şufayrī', value: 'Şufayrī'},
  {label: '‘Urqūb Juwayza', value: '‘Urqūb Juwayza'},
  {label: 'Ḩattā', value: 'Ḩattā'},
  {label: 'Al Lusaylī', value: 'Al Lusaylī'},
  {label: 'Ḩayl', value: 'Ḩayl'},
  {label: 'Warīsān', value: 'Warīsān'},
  {label: 'Muḑayfī', value: 'Muḑayfī'},
  {label: 'Rafā‘', value: 'Rafā‘'},
  {label: 'Lūlayyah', value: 'Lūlayyah'},
  {label: 'Wādī Shī', value: 'Wādī Shī'},
  {label: 'Ash Shu‘ayb', value: 'Ash Shu‘ayb'},
  {label: 'Ḩiyāwah', value: 'Ḩiyāwah'},
  {label: 'Ar Rufayşah', value: 'Ar Rufayşah'},
  {label: 'Shīs', value: 'Shīs'},
  {label: 'Al Jazīrah', value: 'Al Jazīrah'},
  {label: 'Al Ḩamrīyah', value: 'Al Ḩamrīyah'},
  {label: 'Adh Dhayd', value: 'Adh Dhayd'},
  {label: 'Al ‘Awdah', value: 'Al ‘Awdah'},
  {label: 'Qidfa', value: 'Qidfa'},
  {label: 'Ţayyibah', value: 'Ţayyibah'},
  {label: 'Biţnah', value: 'Biţnah'},
  {label: 'Mu‘tariḑah', value: 'Mu‘tariḑah'},
  {label: 'Theeb', value: 'Theeb'},
  {label: 'Wa‘bayn', value: 'Wa‘bayn'},
  {label: 'Al Qurayyah', value: 'Al Qurayyah'},
  {label: 'Al Manāmah', value: 'Al Manāmah'},
  {label: '‘Abādilah', value: '‘Abādilah'},
  {label: 'Ghurfah', value: 'Ghurfah'},
  {label: 'Ḩayl', value: 'Ḩayl'},
  {label: 'Ghayl', value: 'Ghayl'},
  {label: 'Sā’if', value: 'Sā’if'},
  {label: 'Far‘ah', value: 'Far‘ah'},
  {label: 'Mukhtaraqah', value: 'Mukhtaraqah'},
  {label: 'Yalah', value: 'Yalah'},
  {label: 'Rughaylāt', value: 'Rughaylāt'},
  {label: 'Tawian', value: 'Tawian'},
  {label: 'Ḩafarah', value: 'Ḩafarah'},
  {label: 'Ḩārat Zuţūţ', value: 'Ḩārat Zuţūţ'},
  {label: 'Khawr Kalbā', value: 'Khawr Kalbā'},
  {label: 'Al ‘Uyaynah', value: 'Al ‘Uyaynah'},
  {label: 'Rūl Ḑadnā', value: 'Rūl Ḑadnā'},
  {label: '‘Uqayr', value: '‘Uqayr'},
  {label: 'Al Fuqait', value: 'Al Fuqait'},
  {label: 'Shawīyah', value: 'Shawīyah'},
  {label: 'Ḩarrah', value: 'Ḩarrah'},
  {label: 'Dibā', value: 'Dibā'},
  {label: 'Sinnah', value: 'Sinnah'},
  {label: 'Dūb', value: 'Dūb'},
  {label: 'Sram', value: 'Sram'},
  {label: '‘Asamah', value: '‘Asamah'},
  {label: 'Al ‘Ayn al Ghumūr', value: 'Al ‘Ayn al Ghumūr'},
  {label: 'Şūr', value: 'Şūr'},
  {label: 'Waḩlah', value: 'Waḩlah'},
  {label: 'Thoban', value: 'Thoban'},
  {label: 'Al Gissemari', value: 'Al Gissemari'},
  {label: 'Murbaḩ', value: 'Murbaḩ'},
  {label: 'Ḩayāt', value: 'Ḩayāt'},
  {label: 'Khulaybīyah', value: 'Khulaybīyah'},
  {label: 'Z̧anḩah', value: 'Z̧anḩah'},
  {label: 'Saqamqam', value: 'Saqamqam'},
  {label: 'Ḑāhir', value: 'Ḑāhir'},
  {label: 'Jareef', value: 'Jareef'},
  {label: 'Girath', value: 'Girath'},
  {label: 'Riyāmah', value: 'Riyāmah'},
  {label: 'Al Kubūs', value: 'Al Kubūs'},
  {label: '‘Ashashah', value: '‘Ashashah'},
  {label: 'Ḑadnā', value: 'Ḑadnā'},
  {label: '‘Aqqah', value: '‘Aqqah'},
  {label: 'Ras Dibba', value: 'Ras Dibba'},
  {label: 'Nuhayy', value: 'Nuhayy'},
  {label: 'Ḑab‘ah', value: 'Ḑab‘ah'},
  {label: 'Murbaḑ', value: 'Murbaḑ'},
  {label: 'Şafad', value: 'Şafad'},
  {label: 'Ţarīqat Ja‘d', value: 'Ţarīqat Ja‘d'},
];
